  # List of Amazon Linux AMIs (e.g. amzn-ami-pv-2013.09.2.x86_64-ebs).
  # Generated by tools/ami-ids/ami-ids.
  def aws_amis(aws)
    aws.region_config 'ap-northeast-1', :ami => 'ami-0d13700c'
    aws.region_config 'ap-southeast-1', :ami => 'ami-b4baeee6'
    aws.region_config 'ap-southeast-2', :ami => 'ami-5ba83761'
    aws.region_config 'eu-west-1',      :ami => 'ami-5256b825'
    aws.region_config 'sa-east-1',      :ami => 'ami-c99130d4'
    aws.region_config 'us-east-1',      :ami => 'ami-bba18dd2'
    aws.region_config 'us-west-1',      :ami => 'ami-a43909e1'
    aws.region_config 'us-west-2',      :ami => 'ami-ccf297fc'
  end