#!/bin/bash -e

function log() {
  local msg=$1
  local opts=$2
  local time=`date +%H:%M:%S`
  echo $opts "$time $msg"
}

log "Running Berkshelf to install Chef cookbook dependencies..."
berks install -p cookbooks/

if vagrant status | grep -q 'not created'; then
  log "No instance(s) found, creating..."
  start_time=$(date +%s)
  VAGRANT_AWS_INSTANCE_TYPE=t1.micro vagrant up --provider=aws
  stop_time=$(date +%s)
  log "Vagrant took $(($stop_time - $start_time))s"
else
  log "Found existing instance"
fi

log "SSH-ing into the instance..."
vagrant ssh
